/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  Auth: {
    region: 'us-east-1',
    userPoolId: 'us-east-1_ktIo3hIqV',
    userPoolWebClientId: '56q74huoqpdi2pm48cf60t0js0',
  },
};

export default awsmobile;
